[[redirects]]
  from = "/customers/*"
  to = "https://sandbox.asaas.com/api/v3/customers/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
  }

[[redirects]]
  from = "/payments/*"
  to = "https://sandbox.asaas.com/api/v3/payments/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
  }


[[redirects]]
  from = "/addressKeys/*"
  to = "https://sandbox.asaas.com/api/v3/pix/addressKeys/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
