[[redirects]]
  from = "/customers/*"
  to = "https://sandbox.asaas.com/api/v3/customers/:splat"
  status = 200
  force = true
  

[[redirects]]
  from = "/payments/*"
  to = "https://sandbox.asaas.com/api/v3/payments/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/addressKeys/*"
  to = "https://sandbox.asaas.com/api/v3/pix/addressKeys/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
