import {
  aparelhoJantar,
  batedeiraPreta,
  bule,
  camera,
  campoCama,
  centriguga,
  churrasqueira,
  coifa,
  edredrom,
  espremedor,
  faqueiro,
  fechadura,
  ferro,
  frigideiraAntiaderente,
  fritadeiraEletrica,
  geladeira,
  lavadora,
  maquinaCafe,
  microondas,
  panelaEletrica,
  robo,
  tabuaMadeira,
  tvHd,
  tvLed,
  vaso,
  viagemCancum,
  volcher,
  cooktop,
} from '../assets/products'

export const productsLists = [
  {
    id: 1,
    name: 'Batedeira Preta',
    price: 350 * 100,
    image: batedeiraPreta,
  },
  {
    id: 2,
    name: 'Aparelho de Jantar',
    price: 499 * 100,
    image: aparelhoJantar,
  },
  {
    id: 3,
    name: 'Bule',
    price: 59 * 100,
    image: bule,
  },
  {
    id: 4,
    name: 'Camera Digital',
    price: 799 * 100,
    image: camera,
  },
  {
    id: 5,
    name: 'Jogo de Cama',
    price: 469.99 * 100,
    image: campoCama,
  },
  {
    id: 6,
    name: 'Centrifuga',
    price: 209.99 * 100,
    image: centriguga,
  },
  {
    id: 7,
    name: 'Churrasqueira Elétrica',
    price: 198.99 * 100,
    image: churrasqueira,
  },
  {
    id: 8,
    name: 'Coifa de Parede',
    price: 628.06 * 100,
    image: coifa,
  },
  {
    id: 9,
    name: 'Edredom 300 fios',
    price: 281.51 * 100,
    image: edredrom,
  },
  {
    id: 10,
    name: 'Espremedor de Frutas',
    price: 154.87 * 100,
    image: espremedor,
  },
  {
    id: 11,
    name: 'Faqueiro de Bambu',
    price: 205.47 * 100,
    image: faqueiro,
  },
  {
    id: 12,
    name: 'Fechadura Digital',
    price: 266.75 * 100,
    image: fechadura,
  },

  {
    id: 13,
    name: 'Frigideira Antiaderente',
    price: 126.55 * 100,
    image: frigideiraAntiaderente,
  },
  {
    id: 14,
    name: 'Fritadeira Elétrica',
    price: 420.67 * 100,
    image: fritadeiraEletrica,
  },
  {
    id: 15,
    name: 'Geladeira Inox',
    price: 2793 * 100,
    image: geladeira,
  },
  {
    id: 16,
    name: 'Lavadora e Secadora de Roupas',
    price: 2849.05 * 100,
    image: lavadora,
  },
  {
    id: 17,
    name: 'Maquina de Café',
    price: 499 * 100,
    image: maquinaCafe,
  },
  {
    id: 18,
    name: 'Microondas Inox',
    price: 648.99 * 100,
    image: microondas,
  },
  {
    id: 19,
    name: 'Panela Elétrica',
    price: 219.99 * 100,
    image: panelaEletrica,
  },
  {
    id: 20,
    name: 'Robo Aspirador',
    price: 1699.99 * 100,
    image: robo,
  },
  {
    id: 21,
    name: 'Tábua de Madeira',
    price: 294.9 * 100,
    image: tabuaMadeira,
  },
  {
    id: 22,
    name: 'TV Led 29"',
    price: 888.97 * 100,
    image: tvLed,
  },
  {
    id: 23,
    name: 'TV Ultra HD 4K 43"',
    price: 1998.99 * 100,
    image: tvHd,
  },
  {
    id: 24,
    name: 'Lua de Mel',
    price: 4590 * 100,
    image: viagemCancum,
  },
  {
    id: 25,
    name: 'Ferro de Passar',
    price: 73.8 * 100,
    image: ferro,
  },
  {
    id: 26,
    name: 'Vaso de Flores',
    price: 76.09 * 100,
    image: vaso,
  },
  {
    id: 27,
    name: '_Voucher 100 reais',
    price: 100 * 100,
    image: volcher,
  },
  {
    id: 29,
    name: '_Voucher 250 reais',
    price: 250 * 100,
    image: volcher,
  },
  {
    id: 30,
    name: '_Voucher 500 reais',
    price: 500 * 100,
    image: volcher,
  },
  {
    id: 31,
    name: '_Voucher 1000 reais',
    price: 1000 * 100,
    image: volcher,
  },
  {
    id: 32,
    name: 'Cooktop Elétrico',
    price: 1599 * 100,
    image: cooktop,
  },
]
